/**
 * ddlforge - Live Schema Drift Introspection
 *
 * Performs non-locking catalog snapshot queries against `pg_catalog` directly
 * (bypassing `information_schema` overhead and inaccuracies) under REPEATABLE READ READ ONLY.
 * Includes defensive self-canceling lock contention detection to immediately yield
 * if blocking live OLTP write transactions.
 */

import type { PgClientLike } from '../cluster/advisory.js';

export interface CatalogColumn {
  name: string;
  dataType: string;
  isNotNull: boolean;
  identityType: string; // 'a' = generated always, 'd' = generated by default, '' = none
  defaultExpr: string | null;
  generatedType: string; // 's' = stored, '' = none
}

export interface CatalogTable {
  schema: string;
  name: string;
  kind: string; // 'r' = normal table, 'p' = partitioned table, 'v' = view
  columns: CatalogColumn[];
  isPartitioned: boolean;
}

export interface CatalogIndex {
  schema: string;
  table: string;
  name: string;
  isUnique: boolean;
  isPrimary: boolean;
  isValid: boolean;
  isReady: boolean;
  indexDef: string;
  predicate: string | null;
  accessMethod: string;
}

export interface CatalogConstraint {
  schema: string;
  table: string;
  name: string;
  type: 'p' | 'u' | 'c' | 'f' | 't' | 'x'; // p=primary, u=unique, c=check, f=foreign key
  isValidated: boolean; // convalidated: false = NOT VALID
  definition: string;
  foreignTableSchema: string | null;
  foreignTableName: string | null;
}

export interface CatalogPartition {
  parentSchema: string;
  parentTable: string;
  childSchema: string;
  childTable: string;
  partitionBound: string;
  depth: number;
}

export interface CatalogEnum {
  schema: string;
  name: string;
  labels: string[];
}

export interface CatalogSchema {
  tables: CatalogTable[];
  indexes: CatalogIndex[];
  constraints: CatalogConstraint[];
  partitions: CatalogPartition[];
  enums: CatalogEnum[];
}

export interface CatalogIntrospectOptions {
  schemas?: string[]; // default: ['public']
  checkContention?: boolean; // default: true
  lockTimeout?: string; // default: '250ms'
  statementTimeout?: string; // default: '30s'
}

/**
 * Introspects live PostgreSQL database schema directly from `pg_catalog`.
 *
 * Runs inside a read-only transaction with local strict timeouts and
 * active contention defense to prevent holding up live application workloads.
 */
export async function introspectCatalog(
  client: PgClientLike,
  options: CatalogIntrospectOptions = {}
): Promise<CatalogSchema> {
  const schemas = options.schemas ?? ['public'];
  const lockTimeout = options.lockTimeout ?? '250ms';
  const statementTimeout = options.statementTimeout ?? '30s';
  const checkContention = options.checkContention ?? true;

  // Open non-blocking read-only transaction
  await client.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;');

  try {
    await client.query(`SET LOCAL lock_timeout = '${lockTimeout}';`);
    await client.query(`SET LOCAL statement_timeout = '${statementTimeout}';`);

    if (checkContention) {
      await assertNoContention(client);
    }

    const [rawColumns, rawIndexes, rawConstraints, rawPartitions, rawEnums] = await Promise.all([
      fetchColumns(client, schemas),
      fetchIndexes(client, schemas),
      fetchConstraints(client, schemas),
      fetchPartitions(client, schemas),
      fetchEnums(client, schemas),
    ]);

    if (checkContention) {
      await assertNoContention(client);
    }

    await client.query('COMMIT;');

    // Group raw columns into CatalogTable objects
    const tableMap = new Map<string, CatalogTable>();
    for (const col of rawColumns) {
      const key = `${col.schema_name}.${col.table_name}`;
      let tbl = tableMap.get(key);
      if (!tbl) {
        tbl = {
          schema: col.schema_name,
          name: col.table_name,
          kind: col.table_kind,
          columns: [],
          isPartitioned: col.table_kind === 'p',
        };
        tableMap.set(key, tbl);
      }
      tbl.columns.push({
        name: col.column_name,
        dataType: col.data_type,
        isNotNull: Boolean(col.is_not_null),
        identityType: col.identity_type ?? '',
        defaultExpr: col.default_expr ?? null,
        generatedType: col.generated_type ?? '',
      });
    }

    const indexes: CatalogIndex[] = rawIndexes.map(idx => ({
      schema: idx.schema_name,
      table: idx.table_name,
      name: idx.index_name,
      isUnique: Boolean(idx.is_unique),
      isPrimary: Boolean(idx.is_primary),
      isValid: Boolean(idx.is_valid),
      isReady: Boolean(idx.is_ready),
      indexDef: idx.index_def,
      predicate: idx.predicate_expr ?? null,
      accessMethod: idx.access_method,
    }));

    const constraints: CatalogConstraint[] = rawConstraints.map(con => ({
      schema: con.schema_name,
      table: con.table_name,
      name: con.constraint_name,
      type: con.constraint_type as any,
      isValidated: Boolean(con.is_validated),
      definition: con.constraint_def,
      foreignTableSchema: con.foreign_table_schema ?? null,
      foreignTableName: con.foreign_table_name ?? null,
    }));

    const partitions: CatalogPartition[] = rawPartitions.map(p => ({
      parentSchema: p.parent_schema,
      parentTable: p.parent_table,
      childSchema: p.child_schema,
      childTable: p.child_table,
      partitionBound: p.partition_bound ?? '',
      depth: Number(p.depth ?? 1),
    }));

    // Group enums by schema and enum name
    const enumMap = new Map<string, CatalogEnum>();
    for (const row of rawEnums) {
      const key = `${row.schema_name}.${row.enum_name}`;
      let e = enumMap.get(key);
      if (!e) {
        e = {
          schema: row.schema_name,
          name: row.enum_name,
          labels: [],
        };
        enumMap.set(key, e);
      }
      e.labels.push(row.enum_label);
    }

    return {
      tables: Array.from(tableMap.values()),
      indexes,
      constraints,
      partitions,
      enums: Array.from(enumMap.values()),
    };
  } catch (err) {
    await client.query('ROLLBACK;').catch(() => {});
    throw err;
  }
}

/**
 * Checks whether the current introspection backend is blocking other backends.
 * If contention is detected (e.g. on AccessExclusiveLock), self-cancels immediately.
 */
async function assertNoContention(client: PgClientLike): Promise<void> {
  const query = `
    SELECT
      waiter.pid,
      waiter.mode AS waiting_mode,
      act.query AS waiting_query
    FROM pg_locks blocker
    JOIN pg_locks waiter
      ON waiter.relation = blocker.relation
     AND waiter.pid <> blocker.pid
    JOIN pg_stat_activity act ON act.pid = waiter.pid
    WHERE blocker.pid = pg_backend_pid()
      AND blocker.granted = true
      AND waiter.granted = false
      AND (
        waiter.mode IN ('AccessExclusiveLock', 'ExclusiveLock', 'ShareLock')
        OR pg_backend_pid() = ANY(pg_blocking_pids(waiter.pid))
      )
    LIMIT 1;
  `;

  const res = await client.query(query).catch(() => ({ rows: [] }));
  if (res.rows.length > 0) {
    const row = res.rows[0];
    // Immediate self-cancellation
    await client.query('SELECT pg_cancel_backend(pg_backend_pid())').catch(() => {});
    throw new Error(
      `[ddlforge catalog] Yielded: backend is blocking PID ${row['pid']} requesting ${row['waiting_mode']}`
    );
  }
}

async function fetchColumns(client: PgClientLike, schemas: string[]): Promise<any[]> {
  const query = `
    SELECT
      n.nspname AS schema_name,
      c.relname AS table_name,
      c.relkind AS table_kind,
      a.attname AS column_name,
      a.attnum AS column_num,
      format_type(a.atttypid, a.atttypmod) AS data_type,
      a.attnotnull AS is_not_null,
      a.attidentity AS identity_type,
      pg_get_expr(ad.adbin, ad.adrelid) AS default_expr,
      CASE WHEN a.attgenerated != '' THEN a.attgenerated ELSE '' END AS generated_type
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_attribute a ON a.attrelid = c.oid
    LEFT JOIN pg_attrdef ad ON ad.adrelid = c.oid AND ad.adnum = a.attnum
    WHERE n.nspname = ANY($1::text[])
      AND c.relkind IN ('r', 'p')
      AND a.attnum > 0
      AND NOT a.attisdropped
    ORDER BY n.nspname, c.relname, a.attnum;
  `;
  const res = await client.query(query, [schemas]);
  return res.rows;
}

async function fetchIndexes(client: PgClientLike, schemas: string[]): Promise<any[]> {
  const query = `
    SELECT
      n.nspname AS schema_name,
      c.relname AS table_name,
      ic.relname AS index_name,
      i.indisunique AS is_unique,
      i.indisprimary AS is_primary,
      i.indisvalid AS is_valid,
      i.indisready AS is_ready,
      pg_get_indexdef(i.indexrelid) AS index_def,
      pg_get_expr(i.indpred, i.indrelid) AS predicate_expr,
      am.amname AS access_method
    FROM pg_index i
    JOIN pg_class c ON c.oid = i.indrelid
    JOIN pg_class ic ON ic.oid = i.indexrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_am am ON am.oid = ic.relam
    WHERE n.nspname = ANY($1::text[])
      AND c.relkind IN ('r', 'p')
    ORDER BY n.nspname, c.relname, ic.relname;
  `;
  const res = await client.query(query, [schemas]);
  return res.rows;
}

async function fetchConstraints(client: PgClientLike, schemas: string[]): Promise<any[]> {
  const query = `
    SELECT
      n.nspname AS schema_name,
      c.relname AS table_name,
      con.conname AS constraint_name,
      con.contype AS constraint_type,
      con.convalidated AS is_validated,
      pg_get_constraintdef(con.oid, true) AS constraint_def,
      f_n.nspname AS foreign_table_schema,
      f_c.relname AS foreign_table_name
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    LEFT JOIN pg_class f_c ON f_c.oid = con.confrelid
    LEFT JOIN pg_namespace f_n ON f_n.oid = f_c.relnamespace
    WHERE n.nspname = ANY($1::text[])
      AND c.relkind IN ('r', 'p')
    ORDER BY n.nspname, c.relname, con.conname;
  `;
  const res = await client.query(query, [schemas]);
  return res.rows;
}

async function fetchPartitions(client: PgClientLike, schemas: string[]): Promise<any[]> {
  const query = `
    WITH RECURSIVE partition_tree AS (
      SELECT
        pn.nspname AS parent_schema,
        pc.relname AS parent_table,
        pc.oid AS parent_oid,
        cn.nspname AS child_schema,
        cc.relname AS child_table,
        cc.oid AS child_oid,
        pg_get_expr(cc.relpartbound, cc.oid) AS partition_bound,
        1 AS depth
      FROM pg_inherits inh
      JOIN pg_class pc ON pc.oid = inh.inhparent
      JOIN pg_namespace pn ON pn.oid = pc.relnamespace
      JOIN pg_class cc ON cc.oid = inh.inhrelid
      JOIN pg_namespace cn ON cn.oid = cc.relnamespace
      WHERE pn.nspname = ANY($1::text[])

      UNION ALL

      SELECT
        pt.child_schema AS parent_schema,
        pt.child_table AS parent_table,
        pt.child_oid AS parent_oid,
        cn.nspname AS child_schema,
        cc.relname AS child_table,
        cc.oid AS child_oid,
        pg_get_expr(cc.relpartbound, cc.oid) AS partition_bound,
        pt.depth + 1 AS depth
      FROM partition_tree pt
      JOIN pg_inherits inh ON inh.inhparent = pt.child_oid
      JOIN pg_class cc ON cc.oid = inh.inhrelid
      JOIN pg_namespace cn ON cn.oid = cc.relnamespace
    )
    SELECT * FROM partition_tree ORDER BY parent_table, child_table;
  `;
  const res = await client.query(query, [schemas]).catch(() => ({ rows: [] }));
  return res.rows;
}

async function fetchEnums(client: PgClientLike, schemas: string[]): Promise<any[]> {
  const query = `
    SELECT
      n.nspname AS schema_name,
      t.typname AS enum_name,
      e.enumlabel AS enum_label,
      e.enumsortorder AS sort_order
    FROM pg_type t
    JOIN pg_enum e ON e.enumtypid = t.oid
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = ANY($1::text[])
    ORDER BY n.nspname, t.typname, e.enumsortorder;
  `;
  const res = await client.query(query, [schemas]).catch(() => ({ rows: [] }));
  return res.rows;
}
