/**
 * ddlforge v0.7.0 - Comprehensive unit and integration tests for the 5 new rules:
 *   1. identity-sequence-start-with
 *   2. attach-partition-missing-check
 *   3. enum-recreate-table-rewrite
 *   4. non-transactional-in-transaction
 *   5. lock-accumulation-mixed-ddl-dml
 */

import { describe, it } from 'node:test';
import * as assert from 'node:assert/strict';

import { analyzeSql, PostgresLockLevel } from '../../src/index.js';
import {
  identitySequenceStartWithRule,
  attachPartitionMissingCheckRule,
  enumRecreateTableRewriteRule,
  nonTransactionalInTransactionRule,
  lockAccumulationMixedDdlDmlRule,
} from '../../src/rules/index.js';

/* ────────────────────────────────────────────────────────────────────────── */
/* Rule 1: identity-sequence-start-with                                       */
/* ────────────────────────────────────────────────────────────────────────── */

describe('Rule: identity-sequence-start-with', () => {
  it('detects ADD GENERATED ALWAYS AS IDENTITY with START WITH 1 as BLOCKER', () => {
    const sql = `
      ALTER TABLE users
        ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 1);
    `;
    const res = analyzeSql(sql, { rules: [identitySequenceStartWithRule] });
    assert.strictEqual(res.blockersCount, 1);
    const f = res.findings[0];
    assert.strictEqual(f.ruleId, 'identity-sequence-start-with');
    assert.strictEqual(f.severity, 'BLOCKER');
    assert.strictEqual(f.lockLevel, PostgresLockLevel.ACCESS_EXCLUSIVE);
    assert.ok(f.message.includes('"id"'));
    assert.ok(f.message.includes('"users"'));
    assert.ok(f.message.includes('START'));
    assert.ok(f.suggestion.includes('setval'));
    assert.ok(f.suggestion.includes('pg_get_serial_sequence'));
  });

  it('detects ADD GENERATED BY DEFAULT AS IDENTITY with START WITH 0 as BLOCKER', () => {
    const sql = `
      ALTER TABLE orders
        ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 0);
    `;
    const res = analyzeSql(sql, { rules: [identitySequenceStartWithRule] });
    assert.strictEqual(res.blockersCount, 1);
    const f = res.findings[0];
    assert.ok(f.message.includes('"order_id"'));
    assert.ok(f.message.includes('"orders"'));
    assert.ok(f.message.includes('0'));
  });

  it('detects RESTART WITH 1 on identity column as BLOCKER', () => {
    const sql = `
      ALTER TABLE products
        ALTER COLUMN product_id RESTART WITH 1;
    `;
    const res = analyzeSql(sql, { rules: [identitySequenceStartWithRule] });
    assert.strictEqual(res.blockersCount, 1);
    const f = res.findings[0];
    assert.ok(f.message.includes('RESTART'));
    assert.ok(f.message.includes('"product_id"'));
  });

  it('passes ADD GENERATED AS IDENTITY without START WITH (safe)', () => {
    const sql = `
      ALTER TABLE users
        ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
    `;
    const res = analyzeSql(sql, { rules: [identitySequenceStartWithRule] });
    assert.strictEqual(res.blockersCount, 0);
    assert.strictEqual(res.findings.length, 0);
  });

  it('passes ADD GENERATED AS IDENTITY with START WITH 1000 (safe - value > 1)', () => {
    const sql = `
      ALTER TABLE users
        ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 1000);
    `;
    const res = analyzeSql(sql, { rules: [identitySequenceStartWithRule] });
    assert.strictEqual(res.blockersCount, 0);
    assert.strictEqual(res.findings.length, 0);
  });

  it('passes ADD GENERATED AS IDENTITY with RESTART WITH 5000 (safe)', () => {
    const sql = `
      ALTER TABLE orders
        ALTER COLUMN order_id RESTART WITH 5000;
    `;
    const res = analyzeSql(sql, { rules: [identitySequenceStartWithRule] });
    assert.strictEqual(res.blockersCount, 0);
  });

  it('handles schema-qualified table name in identity restart', () => {
    const sql = `
      ALTER TABLE public.accounts
        ALTER COLUMN account_id ADD GENERATED ALWAYS AS IDENTITY (START WITH 1);
    `;
    const res = analyzeSql(sql, { rules: [identitySequenceStartWithRule] });
    assert.strictEqual(res.blockersCount, 1);
    assert.ok(res.findings[0].message.includes('"public.accounts"'));
  });

  it('does not flag CREATE TABLE with inline GENERATED AS IDENTITY', () => {
    const sql = `
      CREATE TABLE users (
        id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL
      );
    `;
    const res = analyzeSql(sql, { rules: [identitySequenceStartWithRule] });
    assert.strictEqual(res.blockersCount, 0);
  });

  it('passes when ignored with directive comment', () => {
    const sql = `
      -- ddlforge-ignore identity-sequence-start-with
      ALTER TABLE users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 1);
    `;
    const res = analyzeSql(sql, { rules: [identitySequenceStartWithRule] });
    assert.strictEqual(res.findings.length, 0);
  });

  it('detects identity-sequence-start-with in analyzeSql default rules', () => {
    const sql = `ALTER TABLE users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 1);`;
    const res = analyzeSql(sql);
    assert.ok(res.findings.some(f => f.ruleId === 'identity-sequence-start-with'));
  });
});

/* ────────────────────────────────────────────────────────────────────────── */
/* Rule 2: attach-partition-missing-check                                     */
/* ────────────────────────────────────────────────────────────────────────── */

describe('Rule: attach-partition-missing-check', () => {
  it('detects bare ATTACH PARTITION without any prior CHECK constraint as BLOCKER', () => {
    const sql = `
      ALTER TABLE measurements
        ATTACH PARTITION measurements_2026
        FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');
    `;
    const res = analyzeSql(sql, { rules: [attachPartitionMissingCheckRule] });
    assert.strictEqual(res.blockersCount, 1);
    const f = res.findings[0];
    assert.strictEqual(f.ruleId, 'attach-partition-missing-check');
    assert.strictEqual(f.severity, 'BLOCKER');
    assert.strictEqual(f.lockLevel, PostgresLockLevel.ACCESS_EXCLUSIVE);
    assert.ok(f.message.includes('"measurements_2026"'));
    assert.ok(f.message.includes('"measurements"'));
    assert.ok(f.suggestion.includes('NOT VALID'));
    assert.ok(f.suggestion.includes('VALIDATE CONSTRAINT'));
  });

  it('passes ATTACH PARTITION when pre-validated CHECK constraint exists', () => {
    const sql = `
      ALTER TABLE measurements_2026 ADD CONSTRAINT chk_bounds
        CHECK (created_at >= '2026-01-01' AND created_at < '2027-01-01') NOT VALID;
      ALTER TABLE measurements_2026 VALIDATE CONSTRAINT chk_bounds;
      ALTER TABLE measurements
        ATTACH PARTITION measurements_2026
        FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');
    `;
    const res = analyzeSql(sql, { rules: [attachPartitionMissingCheckRule] });
    assert.strictEqual(res.blockersCount, 0, `Unexpected findings: ${JSON.stringify(res.findings)}`);
    assert.strictEqual(res.findings.length, 0);
  });

  it('detects ATTACH PARTITION with only NOT VALID check but no VALIDATE (incomplete pattern)', () => {
    const sql = `
      ALTER TABLE measurements_2026 ADD CONSTRAINT chk_bounds
        CHECK (created_at >= '2026-01-01') NOT VALID;
      -- Missing: ALTER TABLE measurements_2026 VALIDATE CONSTRAINT chk_bounds;
      ALTER TABLE measurements
        ATTACH PARTITION measurements_2026
        FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');
    `;
    const res = analyzeSql(sql, { rules: [attachPartitionMissingCheckRule] });
    assert.strictEqual(res.blockersCount, 1, `Expected blocker for missing VALIDATE: ${JSON.stringify(res.findings)}`);
  });

  it('handles IF EXISTS and ONLY modifiers on the parent table', () => {
    const sql = `
      ALTER TABLE IF EXISTS ONLY logs
        ATTACH PARTITION logs_2026
        FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');
    `;
    const res = analyzeSql(sql, { rules: [attachPartitionMissingCheckRule] });
    assert.strictEqual(res.blockersCount, 1);
    assert.ok(res.findings[0].message.includes('"logs_2026"'));
    assert.ok(res.findings[0].message.includes('"logs"'));
  });

  it('does not flag DETACH PARTITION', () => {
    const sql = `
      ALTER TABLE measurements DETACH PARTITION measurements_2025 CONCURRENTLY;
    `;
    const res = analyzeSql(sql, { rules: [attachPartitionMissingCheckRule] });
    assert.strictEqual(res.blockersCount, 0);
  });

  it('does not flag other ALTER TABLE operations', () => {
    const sql = `
      ALTER TABLE users ADD COLUMN middle_name TEXT;
    `;
    const res = analyzeSql(sql, { rules: [attachPartitionMissingCheckRule] });
    assert.strictEqual(res.findings.length, 0);
  });

  it('passes when ignored with directive comment', () => {
    const sql = `
      -- ddlforge-ignore attach-partition-missing-check
      ALTER TABLE measurements ATTACH PARTITION measurements_2026 FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');
    `;
    const res = analyzeSql(sql, { rules: [attachPartitionMissingCheckRule] });
    assert.strictEqual(res.findings.length, 0);
  });

  it('detects attach-partition-missing-check in analyzeSql default rules', () => {
    const sql = `
      ALTER TABLE orders ATTACH PARTITION orders_2026
        FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');
    `;
    const res = analyzeSql(sql);
    assert.ok(res.findings.some(f => f.ruleId === 'attach-partition-missing-check'));
  });
});

/* ────────────────────────────────────────────────────────────────────────── */
/* Rule 3: enum-recreate-table-rewrite                                        */
/* ────────────────────────────────────────────────────────────────────────── */

describe('Rule: enum-recreate-table-rewrite', () => {
  it('detects DROP TYPE + CREATE TYPE AS ENUM + ALTER COLUMN TYPE USING ::text cast as BLOCKER', () => {
    const sql = `
      DROP TYPE user_status;
      CREATE TYPE user_status AS ENUM ('active', 'inactive', 'suspended');
      ALTER TABLE users
        ALTER COLUMN status TYPE user_status USING status::text::user_status;
    `;
    const res = analyzeSql(sql, { rules: [enumRecreateTableRewriteRule] });
    assert.strictEqual(res.blockersCount, 1);
    const f = res.findings[0];
    assert.strictEqual(f.ruleId, 'enum-recreate-table-rewrite');
    assert.strictEqual(f.severity, 'BLOCKER');
    assert.strictEqual(f.lockLevel, PostgresLockLevel.ACCESS_EXCLUSIVE);
    assert.ok(f.message.includes('"status"'));
    assert.ok(f.message.includes('"users"'));
    assert.ok(f.detail.includes('user_status'));
  });

  it('detects enum recreate with IF EXISTS DROP TYPE', () => {
    const sql = `
      DROP TYPE IF EXISTS order_state;
      CREATE TYPE order_state AS ENUM ('pending', 'shipped', 'delivered', 'cancelled');
      ALTER TABLE orders
        ALTER COLUMN state TYPE order_state USING state::varchar::order_state;
    `;
    const res = analyzeSql(sql, { rules: [enumRecreateTableRewriteRule] });
    assert.strictEqual(res.blockersCount, 1);
    assert.ok(res.findings[0].message.includes('"state"'));
    assert.ok(res.findings[0].message.includes('"orders"'));
  });

  it('passes ALTER COLUMN TYPE without enum recreation in the file', () => {
    // No DROP TYPE + CREATE TYPE pair -> no enum recreation -> no flag
    const sql = `
      ALTER TABLE users
        ALTER COLUMN status TYPE text USING status::text;
    `;
    const res = analyzeSql(sql, { rules: [enumRecreateTableRewriteRule] });
    // The enum-recreate rule should not fire since no enum was recreated
    assert.strictEqual(res.findings.filter(f => f.ruleId === 'enum-recreate-table-rewrite').length, 0);
  });

  it('passes DROP TYPE + CREATE TYPE + ALTER COLUMN TYPE without text-cast USING', () => {
    // USING expression doesn't use ::text intermediate cast
    const sql = `
      DROP TYPE priority_level;
      CREATE TYPE priority_level AS ENUM ('low', 'medium', 'high', 'critical');
      ALTER TABLE tasks
        ALTER COLUMN priority TYPE priority_level;
    `;
    const res = analyzeSql(sql, { rules: [enumRecreateTableRewriteRule] });
    // No text-cast USING -> no flag from this rule (other rules may fire for ALTER COLUMN TYPE)
    assert.strictEqual(res.findings.filter(f => f.ruleId === 'enum-recreate-table-rewrite').length, 0);
  });

  it('suggestion mentions ALTER TYPE RENAME VALUE for PG16+', () => {
    const sql = `
      DROP TYPE user_status;
      CREATE TYPE user_status AS ENUM ('active', 'inactive', 'suspended');
      ALTER TABLE users
        ALTER COLUMN status TYPE user_status USING status::text::user_status;
    `;
    const res = analyzeSql(sql, { rules: [enumRecreateTableRewriteRule], pgVersion: 16 });
    assert.strictEqual(res.blockersCount, 1);
    assert.ok(res.findings[0].suggestion.includes('RENAME VALUE'));
  });

  it('suggestion mentions application-layer restriction for PG < 16', () => {
    const sql = `
      DROP TYPE user_status;
      CREATE TYPE user_status AS ENUM ('active', 'inactive', 'suspended');
      ALTER TABLE users
        ALTER COLUMN status TYPE user_status USING status::text::user_status;
    `;
    const res = analyzeSql(sql, { rules: [enumRecreateTableRewriteRule], pgVersion: 15 });
    assert.strictEqual(res.blockersCount, 1);
    assert.ok(res.findings[0].suggestion.includes('application'));
  });

  it('passes when ignored with directive comment', () => {
    const sql = `
      DROP TYPE user_status;
      CREATE TYPE user_status AS ENUM ('active', 'inactive');
      -- ddlforge-ignore enum-recreate-table-rewrite
      ALTER TABLE users ALTER COLUMN status TYPE user_status USING status::text::user_status;
    `;
    const res = analyzeSql(sql, { rules: [enumRecreateTableRewriteRule] });
    assert.strictEqual(res.findings.length, 0);
  });

  it('detects enum-recreate-table-rewrite in analyzeSql default rules', () => {
    const sql = `
      DROP TYPE status_type;
      CREATE TYPE status_type AS ENUM ('a', 'b');
      ALTER TABLE t ALTER COLUMN s TYPE status_type USING s::text::status_type;
    `;
    const res = analyzeSql(sql);
    assert.ok(res.findings.some(f => f.ruleId === 'enum-recreate-table-rewrite'));
  });
});

/* ────────────────────────────────────────────────────────────────────────── */
/* Rule 4: non-transactional-in-transaction                                   */
/* ────────────────────────────────────────────────────────────────────────── */

describe('Rule: non-transactional-in-transaction', () => {
  it('detects REINDEX CONCURRENTLY inside BEGIN...COMMIT as BLOCKER', () => {
    const sql = `
      BEGIN;
      REINDEX TABLE CONCURRENTLY users;
      COMMIT;
    `;
    const res = analyzeSql(sql, { rules: [nonTransactionalInTransactionRule] });
    assert.strictEqual(res.blockersCount, 1);
    const f = res.findings[0];
    assert.strictEqual(f.ruleId, 'non-transactional-in-transaction');
    assert.strictEqual(f.severity, 'BLOCKER');
    assert.ok(f.message.includes('REINDEX CONCURRENTLY'));
    assert.ok(f.message.includes('SQLSTATE 25001'));
    assert.ok(f.detail.includes('transaction block'));
  });

  it('detects VACUUM inside BEGIN...COMMIT as BLOCKER', () => {
    const sql = `
      BEGIN;
      VACUUM ANALYZE users;
      COMMIT;
    `;
    const res = analyzeSql(sql, { rules: [nonTransactionalInTransactionRule] });
    assert.strictEqual(res.blockersCount, 1);
    assert.ok(res.findings[0].message.includes('VACUUM'));
  });

  it('detects ALTER TYPE ... ADD VALUE inside BEGIN...COMMIT as BLOCKER', () => {
    const sql = `
      BEGIN;
      ALTER TYPE user_role ADD VALUE 'superadmin';
      COMMIT;
    `;
    const res = analyzeSql(sql, { rules: [nonTransactionalInTransactionRule] });
    assert.strictEqual(res.blockersCount, 1);
    assert.ok(res.findings[0].message.includes('ALTER TYPE ... ADD VALUE'));
  });

  it('detects REINDEX CONCURRENTLY in START TRANSACTION...END block', () => {
    const sql = `
      START TRANSACTION;
      REINDEX INDEX CONCURRENTLY idx_orders;
      END;
    `;
    const res = analyzeSql(sql, { rules: [nonTransactionalInTransactionRule] });
    assert.strictEqual(res.blockersCount, 1);
  });

  it('detects REINDEX CONCURRENTLY in Prisma migration without pragma', () => {
    const sql = `REINDEX TABLE CONCURRENTLY users;`;
    const res = analyzeSql(sql, {
      rules: [nonTransactionalInTransactionRule],
      filePath: 'prisma/migrations/20260918_reindex/migration.sql',
    });
    assert.strictEqual(res.blockersCount, 1);
    assert.ok(res.findings[0].message.includes('REINDEX CONCURRENTLY'));
    assert.ok(res.findings[0].message.includes('prisma-migrate-disable-next-transaction'));
  });

  it('passes REINDEX CONCURRENTLY in Prisma migration WITH prisma-migrate-disable-next-transaction', () => {
    const sql = `
      -- prisma-migrate-disable-next-transaction
      REINDEX TABLE CONCURRENTLY users;
    `;
    const res = analyzeSql(sql, {
      rules: [nonTransactionalInTransactionRule],
      filePath: 'prisma/migrations/20260918_reindex/migration.sql',
    });
    assert.strictEqual(res.blockersCount, 0);
    assert.strictEqual(res.findings.length, 0);
  });

  it('passes REINDEX CONCURRENTLY in Prisma migration WITH legacy prisma:no-transaction', () => {
    const sql = `
      -- prisma:no-transaction
      REINDEX TABLE CONCURRENTLY users;
    `;
    const res = analyzeSql(sql, {
      rules: [nonTransactionalInTransactionRule],
      filePath: 'prisma/migrations/20260918_reindex/migration.sql',
    });
    assert.strictEqual(res.blockersCount, 0);
  });

  it('passes VACUUM standalone (no transaction)', () => {
    const sql = `VACUUM ANALYZE users;`;
    const res = analyzeSql(sql, { rules: [nonTransactionalInTransactionRule] });
    assert.strictEqual(res.blockersCount, 0);
  });

  it('passes REINDEX CONCURRENTLY standalone (no transaction)', () => {
    const sql = `REINDEX TABLE CONCURRENTLY users;`;
    const res = analyzeSql(sql, { rules: [nonTransactionalInTransactionRule] });
    assert.strictEqual(res.blockersCount, 0);
    assert.strictEqual(res.findings.length, 0);
  });

  it('passes CREATE INDEX (non-concurrent) inside transaction', () => {
    const sql = `
      BEGIN;
      CREATE INDEX idx_users_email ON users (email);
      COMMIT;
    `;
    const res = analyzeSql(sql, { rules: [nonTransactionalInTransactionRule] });
    assert.strictEqual(res.blockersCount, 0);
  });

  it('passes when ignored with directive comment', () => {
    const sql = `
      BEGIN;
      -- ddlforge-ignore non-transactional-in-transaction
      VACUUM ANALYZE users;
      COMMIT;
    `;
    const res = analyzeSql(sql, { rules: [nonTransactionalInTransactionRule] });
    assert.strictEqual(res.findings.length, 0);
  });

  it('detects multiple non-transactional statements inside a single transaction', () => {
    const sql = `
      BEGIN;
      REINDEX TABLE CONCURRENTLY a;
      VACUUM b;
      COMMIT;
    `;
    const res = analyzeSql(sql, { rules: [nonTransactionalInTransactionRule] });
    assert.ok(res.blockersCount >= 2, `Expected at least 2 blockers, got ${res.blockersCount}`);
  });

  it('detects non-transactional-in-transaction in analyzeSql default rules for REINDEX CONCURRENTLY in tx', () => {
    const sql = `
      BEGIN;
      REINDEX TABLE CONCURRENTLY t;
      COMMIT;
    `;
    const res = analyzeSql(sql);
    // Should fire both concurrent-index-in-transaction and non-transactional-in-transaction
    assert.ok(res.findings.some(f => f.ruleId === 'non-transactional-in-transaction'));
  });
});

/* ────────────────────────────────────────────────────────────────────────── */
/* Rule 5: lock-accumulation-mixed-ddl-dml                                    */
/* ────────────────────────────────────────────────────────────────────────── */

describe('Rule: lock-accumulation-mixed-ddl-dml', () => {
  it('detects ALTER TABLE followed by UPDATE in the same file as BLOCKER', () => {
    const sql = `
      ALTER TABLE users ADD COLUMN last_login TIMESTAMPTZ;
      UPDATE users SET last_login = NOW() WHERE last_login IS NULL;
    `;
    const res = analyzeSql(sql, { rules: [lockAccumulationMixedDdlDmlRule] });
    assert.strictEqual(res.blockersCount, 1);
    const f = res.findings[0];
    assert.strictEqual(f.ruleId, 'lock-accumulation-mixed-ddl-dml');
    assert.strictEqual(f.severity, 'BLOCKER');
    assert.strictEqual(f.lockLevel, PostgresLockLevel.ACCESS_EXCLUSIVE);
    assert.ok(f.message.includes('ALTER TABLE'));
    assert.ok(f.message.includes('UPDATE'));
    assert.ok(f.message.includes('"users"'));
    assert.ok(f.suggestion.includes('Phase 1'));
    assert.ok(f.suggestion.includes('Phase 2'));
  });

  it('detects ALTER TABLE followed by INSERT in the same file as BLOCKER', () => {
    const sql = `
      ALTER TABLE audit_log ADD COLUMN event_type TEXT NOT NULL DEFAULT 'unknown';
      INSERT INTO audit_log (entity_id, event_type) SELECT id, 'migration' FROM entities;
    `;
    const res = analyzeSql(sql, { rules: [lockAccumulationMixedDdlDmlRule] });
    assert.strictEqual(res.blockersCount, 1);
    assert.ok(res.findings[0].message.includes('INSERT'));
    assert.ok(res.findings[0].message.includes('"audit_log"'));
  });

  it('detects ALTER TABLE followed by DELETE in the same file as BLOCKER', () => {
    const sql = `
      ALTER TABLE sessions ADD COLUMN is_valid BOOLEAN DEFAULT TRUE;
      DELETE FROM sessions WHERE created_at < NOW() - INTERVAL '30 days';
    `;
    const res = analyzeSql(sql, { rules: [lockAccumulationMixedDdlDmlRule] });
    assert.strictEqual(res.blockersCount, 1);
    assert.ok(res.findings[0].message.includes('DELETE'));
    assert.ok(res.findings[0].message.includes('"sessions"'));
  });

  it('detects DDL + DML inside explicit BEGIN...COMMIT block as BLOCKER', () => {
    const sql = `
      BEGIN;
      ALTER TABLE products ADD COLUMN discount_rate NUMERIC(5,2) DEFAULT 0;
      UPDATE products SET discount_rate = 0.1 WHERE category = 'sale';
      COMMIT;
    `;
    const res = analyzeSql(sql, { rules: [lockAccumulationMixedDdlDmlRule] });
    assert.strictEqual(res.blockersCount, 1);
    assert.ok(res.findings[0].message.includes('"products"'));
  });

  it('passes when DML comes BEFORE DDL in same file (no lock accumulation)', () => {
    // DML before DDL: DDL lock is not yet acquired when DML runs
    const sql = `
      UPDATE users SET last_login = NOW() WHERE last_login IS NULL;
      ALTER TABLE users ADD COLUMN last_login TIMESTAMPTZ;
    `;
    const res = analyzeSql(sql, { rules: [lockAccumulationMixedDdlDmlRule] });
    assert.strictEqual(res.findings.filter(f => f.ruleId === 'lock-accumulation-mixed-ddl-dml').length, 0);
  });

  it('passes pure DDL-only migration (no DML)', () => {
    const sql = `
      ALTER TABLE users ADD COLUMN middle_name TEXT;
      ALTER TABLE users ADD COLUMN nickname TEXT;
    `;
    const res = analyzeSql(sql, { rules: [lockAccumulationMixedDdlDmlRule] });
    assert.strictEqual(res.findings.filter(f => f.ruleId === 'lock-accumulation-mixed-ddl-dml').length, 0);
  });

  it('passes pure DML-only migration (no DDL)', () => {
    const sql = `
      UPDATE users SET active = true WHERE active IS NULL;
      DELETE FROM sessions WHERE expired_at < NOW();
    `;
    const res = analyzeSql(sql, { rules: [lockAccumulationMixedDdlDmlRule] });
    assert.strictEqual(res.findings.filter(f => f.ruleId === 'lock-accumulation-mixed-ddl-dml').length, 0);
  });

  it('passes SELECT statement after ALTER TABLE (reads are not DML lock accumulators)', () => {
    const sql = `
      ALTER TABLE users ADD COLUMN age INT;
      SELECT COUNT(*) FROM users;
    `;
    const res = analyzeSql(sql, { rules: [lockAccumulationMixedDdlDmlRule] });
    assert.strictEqual(res.findings.filter(f => f.ruleId === 'lock-accumulation-mixed-ddl-dml').length, 0);
  });

  it('detects multiple DDL+DML pairs in the same migration file', () => {
    const sql = `
      ALTER TABLE users ADD COLUMN col1 TEXT;
      UPDATE users SET col1 = 'x';
      ALTER TABLE orders ADD COLUMN col2 TEXT;
      INSERT INTO orders (id) SELECT id FROM old_orders;
    `;
    const res = analyzeSql(sql, { rules: [lockAccumulationMixedDdlDmlRule] });
    // Should detect at least 2 findings (one per DDL+DML pair)
    assert.ok(
      res.findings.filter(f => f.ruleId === 'lock-accumulation-mixed-ddl-dml').length >= 2,
      `Expected at least 2 findings, got ${res.findings.length}`
    );
  });

  it('passes when ignored with directive comment on the DML statement', () => {
    const sql = `
      ALTER TABLE users ADD COLUMN last_login TIMESTAMPTZ;
      -- ddlforge-ignore lock-accumulation-mixed-ddl-dml
      UPDATE users SET last_login = NOW() WHERE last_login IS NULL;
    `;
    const res = analyzeSql(sql, { rules: [lockAccumulationMixedDdlDmlRule] });
    assert.strictEqual(res.findings.filter(f => f.ruleId === 'lock-accumulation-mixed-ddl-dml').length, 0);
  });

  it('detects lock-accumulation-mixed-ddl-dml in analyzeSql default rules', () => {
    const sql = `
      ALTER TABLE users ADD COLUMN score INT DEFAULT 0;
      UPDATE users SET score = 100 WHERE score = 0;
    `;
    const res = analyzeSql(sql);
    assert.ok(res.findings.some(f => f.ruleId === 'lock-accumulation-mixed-ddl-dml'));
  });
});

/* ────────────────────────────────────────────────────────────────────────── */
/* Adversarial & Multi-Rule Integration Tests                                 */
/* ────────────────────────────────────────────────────────────────────────── */

describe('v0.7.0 Adversarial & Multi-Rule Integration', () => {
  it('detects all 5 v0.7.0 rule violations in a single adversarial ORM migration', () => {
    const sql = `
      -- 1. identity sequence start with 1
      ALTER TABLE users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 1);

      -- 2. attach partition without pre-validated check
      ALTER TABLE measurements ATTACH PARTITION measurements_2026
        FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');

      -- 3. enum recreate + column type rewrite with text cast
      DROP TYPE account_status;
      CREATE TYPE account_status AS ENUM ('active', 'inactive', 'banned');
      ALTER TABLE accounts ALTER COLUMN status TYPE account_status USING status::text::account_status;

      -- 4. non-transactional inside explicit transaction (VACUUM)
      BEGIN;
      VACUUM ANALYZE users;
      COMMIT;

      -- 5. lock accumulation: DDL + DML
      ALTER TABLE orders ADD COLUMN processed BOOLEAN DEFAULT FALSE;
      UPDATE orders SET processed = TRUE WHERE created_at < NOW() - INTERVAL '1 year';
    `;

    const res = analyzeSql(sql);
    const v070RuleIds = new Set([
      'identity-sequence-start-with',
      'attach-partition-missing-check',
      'enum-recreate-table-rewrite',
      'non-transactional-in-transaction',
      'lock-accumulation-mixed-ddl-dml',
    ]);
    const foundRuleIds = new Set(res.findings.map(f => f.ruleId));

    for (const ruleId of v070RuleIds) {
      assert.ok(
        foundRuleIds.has(ruleId),
        `Expected to find rule ${ruleId}, but found: ${[...foundRuleIds].join(', ')}`
      );
    }
  });

  it('produces 0 findings from v0.7.0 rules for a comprehensive safe migration', () => {
    const sql = `
      -- 1. identity: no explicit START WITH (safe)
      ALTER TABLE users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

      -- 2. attach partition: with pre-validated check (4-phase pattern)
      ALTER TABLE measurements_2026 ADD CONSTRAINT chk_measurements_bounds
        CHECK (created_at >= '2026-01-01' AND created_at < '2027-01-01') NOT VALID;
      ALTER TABLE measurements_2026 VALIDATE CONSTRAINT chk_measurements_bounds;
      ALTER TABLE measurements ATTACH PARTITION measurements_2026
        FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');

      -- 3. enum label addition (not recreation): safe
      ALTER TYPE account_status ADD VALUE IF NOT EXISTS 'suspended';

      -- 4. concurrent index outside transaction (standalone)
      CREATE INDEX CONCURRENTLY idx_users_score ON users (score);

      -- 5. DDL only, no subsequent DML in same file
      ALTER TABLE orders ADD COLUMN processed BOOLEAN DEFAULT FALSE;
    `;

    const res = analyzeSql(sql, { pgVersion: 16 });
    const v070Findings = res.findings.filter(f =>
      ['identity-sequence-start-with', 'attach-partition-missing-check', 'enum-recreate-table-rewrite',
       'non-transactional-in-transaction', 'lock-accumulation-mixed-ddl-dml'].includes(f.ruleId)
    );
    assert.strictEqual(
      v070Findings.length,
      0,
      `Expected 0 v0.7.0 findings for safe migration, got: ${JSON.stringify(v070Findings)}`
    );
  });

  it('does not false positive on keywords inside comments or dollar-quoted function bodies', () => {
    const sql = `
      CREATE OR REPLACE FUNCTION safe_attach() RETURNS void AS $$
      BEGIN
        -- ATTACH PARTITION is mentioned here in a comment
        -- START WITH 1 is mentioned here in a comment
        -- DROP TYPE and CREATE TYPE as ENUM
        -- UPDATE users SET ... is a comment
        RAISE NOTICE 'doing nothing';
      END;
      $$ LANGUAGE plpgsql;
    `;
    const res = analyzeSql(sql);
    const v070Findings = res.findings.filter(f =>
      ['identity-sequence-start-with', 'attach-partition-missing-check', 'enum-recreate-table-rewrite',
       'non-transactional-in-transaction', 'lock-accumulation-mixed-ddl-dml'].includes(f.ruleId)
    );
    assert.strictEqual(
      v070Findings.length,
      0,
      `Unexpected false positive: ${JSON.stringify(v070Findings)}`
    );
  });

  it('handles lowercase SQL and quoted identifiers correctly', () => {
    const sql = `
      alter table "public"."users"
        alter column "id" add generated always as identity (start with 1);
    `;
    const res = analyzeSql(sql, { rules: [identitySequenceStartWithRule] });
    assert.strictEqual(res.blockersCount, 1);
    assert.strictEqual(res.findings[0].ruleId, 'identity-sequence-start-with');
  });
});
